// Phase 3: Marriage Intelligence Service
// Manages Talk Before You Marry, Couple Mode, Risk Signals, Milestones, and First 100 Days.

import { 
  TalkBeforeMarriageTopic, 
  RelationshipRiskSignal, 
  CoupleSpaceState, 
  JourneyMilestone, 
  HundredDaysPrompt, 
  AnnualHealthCheck 
} from '../types/intelligence';

export const INITIAL_TALK_TOPICS: TalkBeforeMarriageTopic[] = [
  {
    id: 'tb_money_01',
    category: 'Money & Finances',
    prompt: 'How do you envision managing finances after marriage — joint pooling, proportional contributions, or separate accounts?',
    guidance: 'Discussing day-to-day budgets, savings buffers, investments, and personal discretionary allowances early prevents subtle financial resentment.',
    userPrivateReflection: 'I believe in having one shared household account for common rent, bills, groceries, and travel, while keeping separate personal accounts for individual spending and savings.',
    isSharedWithPartner: true,
    partnerSharedReflection: 'I love this approach! A proportional contribution to a joint household fund while maintaining personal financial independence feels balanced and fair.',
    status: 'shared',
    updatedAt: '2026-10-02',
  },
  {
    id: 'tb_parents_02',
    category: 'Parents & Family Duties',
    prompt: 'How often do you envision visiting or hosting extended family, and how will elder care responsibilities be shared as parents age?',
    guidance: 'Honoring cultural obligations to parents while maintaining healthy couple autonomy is vital in Indian marriages.',
    userPrivateReflection: 'My parents live in Jaipur and I visit every 6-8 weeks. As they grow older, I want them to feel welcome to stay with us whenever needed.',
    isSharedWithPartner: true,
    partnerSharedReflection: 'Completely agree. My parents are in Pune and I value close family relationships. Having open doors for both sets of parents is very important to me.',
    status: 'shared',
    updatedAt: '2026-10-03',
  },
  {
    id: 'tb_kids_03',
    category: 'Children & Parenting',
    prompt: 'What are your hopes and timelines regarding children, and how would parenting duties or career pauses be balanced?',
    guidance: 'Align on whether you both want children, potential timelines (e.g. 2-3 years post-wedding), and shared childcare philosophy.',
    userPrivateReflection: 'I would love to have 1 or 2 children, perhaps 2 to 3 years after settling into marriage. I want to be an active, hands-on father with equal diaper, school, and bedtime duties.',
    isSharedWithPartner: false,
    status: 'private_draft',
    updatedAt: '2026-10-04',
  },
  {
    id: 'tb_career_04',
    category: 'Career & Relocation',
    prompt: 'If a major career or relocation opportunity arises in another city or abroad for either partner, how will we make the decision?',
    guidance: 'Clarifies mutual career respect and establishes a framework for balancing two demanding professional trajectories.',
    userPrivateReflection: 'I am open to relocating if an opportunity benefits both of us, provided we discuss it jointly without unilateral pressure.',
    isSharedWithPartner: false,
    status: 'private_draft',
    updatedAt: '2026-10-05',
  },
  {
    id: 'tb_conflict_05',
    category: 'Conflict & Communication',
    prompt: 'When you are upset or during a heated disagreement, do you prefer immediate discussion or taking quiet time first to process?',
    guidance: 'Understanding whether your partner is a "processor" or an "immediate resolver" prevents misinterpreting pause time as emotional withdrawal.',
    userPrivateReflection: 'When overwhelmed, I sometimes need 30 minutes to calm down before finding gentle words. I promise not to stonewall if you give me that breathing room.',
    isSharedWithPartner: true,
    partnerSharedReflection: 'I tend to want to resolve things right away, but understanding your need for a brief breather will help me not panic or push during disagreements.',
    status: 'shared',
    updatedAt: '2026-10-06',
  },
  {
    id: 'tb_living_06',
    category: 'Living Arrangements',
    prompt: 'Do you prefer living independently as a nuclear unit, living with parents in a joint household, or living in close proximity?',
    guidance: 'Clear living preferences avoid unspoken expectations regarding day-to-day household dynamics.',
    userPrivateReflection: 'I prefer living independently as a couple in Bangalore, while keeping our homes easily accessible for extended family visits.',
    isSharedWithPartner: false,
    status: 'private_draft',
  },
];

export const INITIAL_RISK_SIGNALS: RelationshipRiskSignal[] = [
  {
    id: 'rs_01',
    title: 'Financial Philosophy Divergence',
    level: 'Needs Discussion (Amber)',
    observation: 'One profile leans towards traditional single-breadwinner assumptions while the other prioritizes dual-career shared budgeting.',
    evidenceSource: 'Expectations Layer • Financial Philosophy field comparison',
    suggestedAction: 'Dedicate an unhurried conversation to how monthly investments, savings targets, and big purchases will be made.',
    questionsToAsk: [
      'What did financial security look like in your family growing up?',
      'How do you feel about joint savings accounts versus separate discretionary spending?',
    ],
    professionalSupportNote: 'Pre-marital financial coaching can help align couples who grew up with distinct money habits.',
  },
  {
    id: 'rs_02',
    title: 'Relocation & Geographic Flexibility',
    level: 'Advisory (Green)',
    observation: 'Current bases are in Bangalore and Pune. Both express preference for current city but have stated willingness to discuss long-term options.',
    evidenceSource: 'Location & Relocation Preferences layer',
    suggestedAction: 'Clarify company transfer flexibility and whether a permanent base in Bangalore works for both careers.',
    questionsToAsk: [
      'Are your current professional roles hybrid or fully office-based?',
      'How would we navigate the first 12 months if one of us needs to transition cities?',
    ],
  },
  {
    id: 'rs_03',
    title: 'Family Boundary & Independence Alignment',
    level: 'Advisory (Green)',
    observation: 'Both profiles indicate moderate-to-liberal family values with nuclear household preferences. Strong mutual resonance observed.',
    evidenceSource: 'Family Layer • Structure & Values parity',
    suggestedAction: 'Affirm mutual agreement on weekend personal time versus extended family commitments.',
    questionsToAsk: [
      'What does a restful Sunday look like for you versus a family commitment day?',
    ],
  },
];

export const INITIAL_JOURNEY_MILESTONES: JourneyMilestone[] = [
  {
    id: 'm_01',
    title: 'Mutual Match & Connected',
    description: 'Both individuals expressed mutual interest and unlocked private conversations.',
    stage: 'Pre-Marriage',
    order: 1,
    completedByUser: true,
    completedByPartner: true,
    isMutualCompleted: true,
    completedAt: '2026-09-18',
  },
  {
    id: 'm_02',
    title: 'ChaanBean Trust Check Review',
    description: 'Both partners reviewed each other’s verified ChaanBean credential badges.',
    stage: 'Pre-Marriage',
    order: 2,
    completedByUser: true,
    completedByPartner: true,
    isMutualCompleted: true,
    completedAt: '2026-09-20',
  },
  {
    id: 'm_03',
    title: 'Know Each Other (Core Values)',
    description: 'Explored personal passions, cultural backgrounds, and life philosophies.',
    stage: 'Pre-Marriage',
    order: 3,
    completedByUser: true,
    completedByPartner: true,
    isMutualCompleted: true,
    completedAt: '2026-09-28',
  },
  {
    id: 'm_04',
    title: 'Important Conversations (Talk Before You Marry)',
    description: 'Reflected on money, children, conflict resolution, and career expectations.',
    stage: 'Pre-Marriage',
    order: 4,
    completedByUser: true,
    completedByPartner: true,
    isMutualCompleted: true,
    completedAt: '2026-10-06',
  },
  {
    id: 'm_05',
    title: 'Family Introduction',
    description: 'Introduced partners to parents and extended family in a welcoming setting.',
    stage: 'Pre-Marriage',
    order: 5,
    completedByUser: true,
    completedByPartner: false,
    isMutualCompleted: false,
  },
  {
    id: 'm_06',
    title: 'Marriage Readiness Alignment',
    description: 'Both partners agree they feel emotionally grounded and ready for lifelong union.',
    stage: 'Pre-Marriage',
    order: 6,
    completedByUser: false,
    completedByPartner: false,
    isMutualCompleted: false,
  },
  {
    id: 'm_07',
    title: 'Formal Engagement (Roka / Sagai)',
    description: 'Celebrated commitment with family blessing.',
    stage: 'Engagement & Wedding',
    order: 7,
    completedByUser: false,
    completedByPartner: false,
    isMutualCompleted: false,
  },
  {
    id: 'm_08',
    title: 'The Sacred Wedding (Vivaha)',
    description: 'United in sacred marriage vows and Saptapadi.',
    stage: 'Engagement & Wedding',
    order: 8,
    completedByUser: false,
    completedByPartner: false,
    isMutualCompleted: false,
  },
  {
    id: 'm_09',
    title: 'First 100 Days Transition Program',
    description: 'Structured 100-day guidance on expectations, communication, and home rhythm.',
    stage: 'Post-Marriage',
    order: 9,
    completedByUser: false,
    completedByPartner: false,
    isMutualCompleted: false,
  },
  {
    id: 'm_10',
    title: 'First Anniversary & Health Check',
    description: 'Yearly check-in on communication, intimacy, finances, and long-term joint dreams.',
    stage: 'Post-Marriage',
    order: 10,
    completedByUser: false,
    completedByPartner: false,
    isMutualCompleted: false,
  },
];

export const INITIAL_HUNDRED_DAYS_PROMPTS: HundredDaysPrompt[] = [
  {
    id: 'hd_01',
    dayRange: 'Days 1–7',
    theme: 'Settling In & Decompressing',
    question: 'What has been the most comforting surprise about waking up together this first week?',
    userResponse: 'The quiet mornings before work, making chai together without any wedding rush.',
    isShared: true,
    partnerResponse: 'Knowing that the long wedding planning is behind us and our real everyday life has begun.',
  },
  {
    id: 'hd_02',
    dayRange: 'Days 8–30',
    theme: 'Communication Rhythms',
    question: 'How do our evening unwinding styles mesh, and do we have enough quiet personal space?',
    userResponse: 'I appreciate reading for 30 minutes in the evening. It recharges me after long office calls.',
    isShared: true,
    partnerResponse: 'I love that we can sit in the same room reading quietly without feeling pressured to talk constantly.',
  },
  {
    id: 'hd_03',
    dayRange: 'Days 31–60',
    theme: 'Money & Household Rhythms',
    question: 'How smoothly is our shared household budget flowing, and does grocery/cooking balance feel fair?',
    userResponse: 'The joint account card has made shared groceries effortless. I want to cook dinner more often on Wednesdays.',
    isShared: false,
  },
  {
    id: 'hd_04',
    dayRange: 'Days 61–90',
    theme: 'Lifestyle & Social Boundaries',
    question: 'Have we balanced couple downtime with visiting extended family and friends this month?',
    userResponse: '',
    isShared: false,
  },
  {
    id: 'hd_05',
    dayRange: 'Days 91–100',
    theme: 'Relationship Health Reflection',
    question: 'Looking back over our first 100 days, what is one ritual we want to keep nurturing for the next year?',
    userResponse: '',
    isShared: false,
  },
];

export const INITIAL_ANNUAL_CHECK: AnnualHealthCheck = {
  year: 1,
  communicationHarmony: 'Deeply Connected',
  financialStressLevel: 'Low / Aligned',
  emotionalCloseness: 'Warm & Present',
  spiritualConnection: 'Nurturing',
  jointGoals: 'Plan a quiet anniversary retreat, purchase our first joint home in Bangalore, and establish regular weekend hiking habits.',
};
