// Phase 5: Pratha Spirituality & Wellbeing Service (Module N)
// Provides authentic Vedic contemplative practices, temple experiences, poojas, 21-day couple journey, and festival calendar.

import { 
  SpiritualPath, 
  DailySankalpa, 
  TempleExperience, 
  PoojaGuide, 
  CoupleJourneyDay, 
  FestivalEvent, 
  MeditationSession 
} from '../types/pratha';

export const TODAY_SANKALPA: DailySankalpa = {
  date: 'Today, 2026-10-09',
  theme: 'Samanasyam (Harmonious Unity of Hearts)',
  slokaOrAffirmation: 'समानो मन्त्रः समितिः समानी समानं मनः सह चित्तमेषाम्। (Rigveda 10.191.3)',
  meaning: 'May our purpose be harmonious, may our gathering be united, may our thoughts be of one mind, and may our hearts beat together in gentle peace.',
  practicePrompt: 'Before beginning your work or family conversations today, pause for 60 seconds of quiet breath. Silently hold the intention of patience and mutual respect for your partner and loved ones.',
  durationMinutes: 3,
};

export const PRATHA_TEMPLES: TempleExperience[] = [
  {
    id: 'temple_meenakshi_01',
    name: 'Meenakshi Sundareswarar Temple',
    deity: 'Goddess Meenakshi (Parvati) & Lord Sundareswarar (Shiva)',
    location: 'Madurai',
    state: 'Tamil Nadu',
    spiritualSignificance: 'The historic epicentre of divine matrimonial harmony, celebrating the celestial wedding (Thirukalyanam) of Meenakshi and Shiva.',
    marriageSignificance: 'Revered across centuries for blessing couples with lifelong marital understanding, equal mutual respect, and prosperous companionship.',
    recommendedSeva: 'Thirukalyanam Archana & Evening Golden Chariot Procession',
    dressCode: 'Traditional Dhoti/Veshti for men; Saree or traditional Salwar for women',
    bestTimings: '06:00 AM – 11:30 AM & 04:30 PM – 09:00 PM',
    bookingStatus: 'available_direct',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'temple_tirupati_02',
    name: 'Tirumala Venkateswara Temple',
    deity: 'Lord Venkateswara (Balaji) & Goddess Padmavathi',
    location: 'Tirupati',
    state: 'Andhra Pradesh',
    spiritualSignificance: 'One of the most sacred pilgrimage shrines on Earth, representing spiritual abundance, devotion, and divine protection.',
    marriageSignificance: 'Newlyweds and couples traditionally undertake darshan together to seek divine blessings for an unshakeable family foundation and ethical wealth.',
    recommendedSeva: 'Kalyanotsavam (Daily Divine Celestial Wedding Seva)',
    dressCode: 'Traditional Indian attire (White Dhoti/Kurta, Saree/Churidar with Dupatta)',
    bestTimings: 'Early morning Suprabhatam or pre-booked Kalyanotsavam slots',
    bookingStatus: 'available_direct',
    imageUrl: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'temple_kashi_03',
    name: 'Kashi Vishwanath & Annapurna Temple',
    deity: 'Lord Shiva (Vishwanath) & Goddess Annapurna',
    location: 'Varanasi',
    state: 'Uttar Pradesh',
    spiritualSignificance: 'The spiritual heart of India along the sacred Ganga, embodying liberation, truth, and cosmic stillness.',
    marriageSignificance: 'Couples visit to offer Ganga jal together and receive Annapurna blessings so that their marital home is always filled with nourishment, hospitality, and tranquility.',
    recommendedSeva: 'Mangala Aarti Darshan & Dampati Ganga Sankalpa Pooja',
    dressCode: 'Modest traditional Indian attire',
    bestTimings: '04:00 AM (Mangala Aarti) or Evening Ganga Aarti at Dashashwamedh',
    bookingStatus: 'available_direct',
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'temple_somnath_04',
    name: 'Somnath Jyotirlinga Temple',
    deity: 'Lord Shiva',
    location: 'Prabhas Patan, Saurashtra',
    state: 'Gujarat',
    spiritualSignificance: 'The eternal First Jyotirlinga overlooking the Arabian Sea, symbolizing resilience, timeless renewal, and unyielding devotion.',
    marriageSignificance: 'Couples seek Somnath blessings for emotional endurance, steadfast commitment through life transitions, and resilience against external storms.',
    recommendedSeva: 'Dhwaja Arohana (Temple Flag Offering) & Someshwar Maha Pooja',
    dressCode: 'Dhoti/Kurta for men; Saree or traditional Indian dress for women',
    bestTimings: '06:00 AM – 09:30 PM (Sound & Light show at 08:00 PM)',
    bookingStatus: 'advisory_only',
    imageUrl: 'https://images.unsplash.com/photo-1621252179027-94459d278660?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'temple_kamakhya_05',
    name: 'Maa Kamakhya Temple',
    deity: 'Goddess Kamakhya (Shakti)',
    location: 'Nilachal Hill, Guwahati',
    state: 'Assam',
    spiritualSignificance: 'The ancient Shakti Peetha celebrating primordial feminine creative power, fertility, and divine love.',
    marriageSignificance: 'Couples visit for blessings of health, biological fertility, emotional renewal, and mutual adoration.',
    recommendedSeva: 'Nitya Pooja & Kumari Pooja offerings',
    dressCode: 'Traditional Indian clothing; leather items strictly prohibited on premises',
    bestTimings: '05:30 AM – 01:00 PM & 02:30 PM – 05:30 PM',
    bookingStatus: 'advisory_only',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
  },
];

export const POOJA_GUIDES: PoojaGuide[] = [
  {
    id: 'pooja_saptapadi_01',
    title: 'The Seven Sacred Steps (Saptapadi): Inner Meaning & Daily Application',
    category: 'wedding_sanskar',
    purpose: 'Understand the seven eternal vows exchanged around the sacred Agni that transform two lives into an indissoluble spiritual partnership.',
    duration: 'Comprehensive reading & reflection (15 mins)',
    recommendedTithi: 'Pre-wedding preparation or every marriage anniversary',
    spiritualMeaning: 'Saptapadi is not mere ceremonial ritual; it is a shared constitutional covenant addressing nourishment, vitality, prosperity, joy, children, seasons of life, and lifelong sacred friendship.',
    samagriList: [
      'Agni Kunda / Brass Diya with pure cow ghee',
      'Akshata (unbroken rice grains mixed with turmeric)',
      'Flowers and betel leaves (Paan & Supari)',
      'Gangajal for purification',
    ],
    stepByStepRitual: [
      'Step 1 (Food & Sustenance): "Together we shall provide noble sustenance and care for our household."',
      'Step 2 (Strength & Health): "Together we shall cultivate physical, mental, and spiritual resilience."',
      'Step 3 (Prosperity & Right Livelihood): "Together we shall earn ethically and share with those in need."',
      'Step 4 (Mutual Joy & Harmony): "Together we shall nurture understanding, music, culture, and laughter."',
      'Step 5 (Family & Future Generations): "Together we shall raise children with courage, wisdom, and kindness."',
      'Step 6 (Seasons & Life Transitions): "Together we shall remain steadfast through life’s winters and springs."',
      'Step 7 (True Spiritual Companionship): "You are my eternal friend (Sakha Saptapada Bhava); we are united in soul."',
    ],
  },
  {
    id: 'pooja_gauri_02',
    title: 'Gauri Pooja: Cultivating Grace & Domestic Calm',
    category: 'pre_wedding',
    purpose: 'Traditional invocation of Goddess Parvati to bless the prospective bride and groom with inner composure, steadfast love, and graceful speech.',
    duration: '30 – 45 mins',
    recommendedTithi: 'Shukla Paksha Tritiya or on the wedding morning',
    spiritualMeaning: 'Gauri symbolizes the highest tapas (dedication) that united with Shiva. Performing this ritual fosters unwavering devotion and peace in home relationships.',
    samagriList: [
      'Idol or picture of Goddess Parvati / Gauri',
      'Turmeric paste (Haldi), Kumkum, Chandan',
      'Red hibiscus or fresh fragrant flowers',
      'Fresh seasonal fruits and sweet kheer offering (Naivedyam)',
      'Brass bell, camphor, and agarbatti',
    ],
    stepByStepRitual: [
      'Begin with Dhyana (contemplation) and Achamana (purification with water).',
      'Invoke Lord Ganesha first to eliminate obstacles.',
      'Offer Chandan, Kumkum, and flowers while chanting the Gauri Gayatri Mantra.',
      'Offer Naivedyam with sincere prayers for harmony with future in-laws and partner.',
      'Conclude with Aarti and take a moment of silent personal reflection.',
    ],
  },
  {
    id: 'pooja_griha_03',
    title: 'Griha Pravesh: Consecrating Your First Shared Home',
    category: 'home_auspicious',
    purpose: 'Cleansing subtle domestic energies and inviting divine abundance into the couple’s living sanctuary.',
    duration: '1.5 – 2 hours',
    recommendedTithi: 'Auspicious Muhurat determined by Shukla Paksha Panchami, Saptami, Dashami, or Ekadashi',
    spiritualMeaning: 'A home is not just concrete and furniture; it is a sacred Kshetra where memories, children, and spiritual calm reside.',
    samagriList: [
      'Mangal Kalash with coconut, mango leaves, and sacred water',
      'Cow milk for the ceremonial boiling over (Ksheera Dhara)',
      'Navadhanya (nine grains) and Panchamrita',
      'Toran of fresh mango leaves for the main doorway',
    ],
    stepByStepRitual: [
      'Step across the threshold with the right foot forward carrying the consecrated Kalash.',
      'Perform Vastu Pooja and Navagraha Shanti to align environmental directions.',
      'Ceremonially boil milk in the kitchen until it gently overflows, signifying unending abundance.',
      'Share sweet Prasad first between spouses, then with family and respected guests.',
    ],
  },
  {
    id: 'pooja_satyanarayan_04',
    title: 'Sri Satyanarayan Katha: Gratitude for Family Harmony',
    category: 'annual_vratha',
    purpose: 'A joyful community and couple thanksgiving pooja dedicated to Lord Vishnu, affirming honesty and ethical conduct.',
    duration: '1 – 1.5 hours',
    recommendedTithi: 'Purnima (Full Moon day) or auspicious weekend',
    spiritualMeaning: 'Satya (Truth) is the foundation of marriage. The Katha recounts lessons on humility, keeping promises, and overcoming arrogance through gratitude.',
    samagriList: [
      'Panchamrit (Milk, Curd, Ghee, Honey, Sugar)',
      'Sheera / Panjiri Prasad prepared with wheat flour, sugar, and banana',
      'Tulsi leaves (mandatory for Lord Vishnu)',
      'Yellow cloth and floral garland for the altar',
    ],
    stepByStepRitual: [
      'Set up the wooden Chowki facing East or North.',
      'Recite the five chapters of Sri Satyanarayan Katha together as a couple.',
      'Sing the Vishnu Aarti accompanied by conch (Shankha) and bell.',
      'Distribute Prasad to family, neighbours, and staff with humility.',
    ],
  },
];

export const INITIAL_COUPLE_JOURNEY: CoupleJourneyDay[] = [
  {
    dayNumber: 1,
    title: 'The Seed of Gratitude',
    theme: 'Gratitude',
    exercise: 'Sit together in a quiet room for 5 minutes without phones. Take 3 deep breaths together.',
    sharedQuestion: 'What is one specific quality in me that made you feel peaceful this past week?',
    completedByUser: true,
    completedByPartner: true,
  },
  {
    dayNumber: 2,
    title: 'Honoring Differences',
    theme: 'Patience',
    exercise: 'Reflect on one habit where you both approach life differently (e.g., speed, punctuality, organizing).',
    sharedQuestion: 'How can we view our difference not as friction, but as complementary balance?',
    completedByUser: true,
    completedByPartner: true,
  },
  {
    dayNumber: 3,
    title: 'Sacred Speech (Vak Shuddhi)',
    theme: 'Patience',
    exercise: 'Practice the Vedic principle of speech: "Satyam Bruyat, Priyam Bruyat" (Speak what is true, speak what is kind).',
    sharedQuestion: 'When you are stressed after work, what words or tone make you feel instantly comforted?',
    completedByUser: true,
    completedByPartner: false,
  },
  {
    dayNumber: 4,
    title: 'Clearing Past Shadows',
    theme: 'Forgiveness',
    exercise: 'Identify any small misunderstanding from the past few days and consciously release it.',
    sharedQuestion: 'Is there anything unsaid that you would like me to listen to with an open heart?',
    completedByUser: false,
    completedByPartner: false,
  },
  {
    dayNumber: 5,
    title: 'Home as a Sanctuary',
    theme: 'Home Sanctuary',
    exercise: 'Light a small ghee diya or scented candle in your living room together.',
    sharedQuestion: 'What is one daily ritual we want to keep sacred in our shared living space?',
    completedByUser: false,
    completedByPartner: false,
  },
  {
    dayNumber: 6,
    title: 'Generosity Beyond Ourselves',
    theme: 'Generosity',
    exercise: 'Plan one small joint act of kindness for someone outside your immediate circle (elderly neighbor, animal shelter, staff).',
    sharedQuestion: 'How does giving together strengthen our bond as a couple?',
    completedByUser: false,
    completedByPartner: false,
  },
  {
    dayNumber: 7,
    title: 'Saptapadi Friendship Check',
    theme: 'Sacred Union',
    exercise: 'Recall the 7th step of Saptapadi: "Sakha Saptapada Bhava" (Become my lifelong friend).',
    sharedQuestion: 'What was our most joyful moment of pure friendship this week?',
    completedByUser: false,
    completedByPartner: false,
  },
];

export const UPCOMING_FESTIVALS: FestivalEvent[] = [
  {
    id: 'fest_karwa_01',
    name: 'Karwa Chauth / Atla Tadde',
    date: '2026-10-29',
    tithi: 'Kartik Krishna Chaturthi',
    category: 'Couple Observance',
    spiritualSignificance: 'A profound traditional festival celebrating mutual longevity, love, and emotional devotion between spouses.',
    coupleRecommendation: 'Observe the fast mutually or celebrate the evening moonrise darshan together with a quiet shared home dinner.',
  },
  {
    id: 'fest_diwali_02',
    name: 'Deepavali & Lakshmi-Ganesh Pooja',
    date: '2026-11-08',
    tithi: 'Kartik Amavasya',
    category: 'Major Festival',
    spiritualSignificance: 'The triumph of spiritual light over darkness and invocation of prosperity, auspiciousness, and domestic peace.',
    coupleRecommendation: 'Light diyas at the threshold together and conduct the household Lakshmi pooja jointly as life partners.',
  },
  {
    id: 'fest_vivaha_03',
    name: 'Vivaha Panchami',
    date: '2026-12-14',
    tithi: 'Margashirsha Shukla Panchami',
    category: 'Auspicious Muhurat Window',
    spiritualSignificance: 'Celebrates the sacred divine marriage of Sri Rama and Mata Sita, symbolizing dharma and selfless love.',
    coupleRecommendation: 'Ideal day for pre-marriage roka/sagai ceremonies, engagement affirmations, or reading Rama-Sita katha.',
  },
  {
    id: 'fest_makar_04',
    name: 'Makar Sankranti & Pongal',
    date: '2027-01-14',
    tithi: 'Magha / Sun enters Makara',
    category: 'Major Festival',
    spiritualSignificance: 'The solar transit marking the arrival of auspicious Uttarayana, harvest abundance, and family renewal.',
    coupleRecommendation: 'Share sesame and jaggery (Til-Gul) with the greeting "Til-gul ghya, aani goad-goad bola" (Speak sweet words all year).',
  },
];

export const MEDITATION_SESSIONS: MeditationSession[] = [
  {
    id: 'med_couple_01',
    title: 'Couple Heart-Coherence Breathing',
    category: 'Couple Coherence',
    durationMinutes: 7,
    guidanceText: 'Synchronize your respiratory rhythm. Sitting opposite each other with closed eyes, breathe in for 4 seconds, hold for 2, and release for 6. Feel the collective heartbeat calm.',
    audioPromptPreview: 'Soft Tibetan singing bowl with gentle flute drone in Raag Bhairav.',
  },
  {
    id: 'med_calm_02',
    title: 'Pre-Wedding & Engagement Anxiety Calming',
    category: 'Wedding Calm',
    durationMinutes: 10,
    guidanceText: 'Wedding preparations can overwhelm the nervous system with logistical stress. This session grounds your awareness in the timeless significance of your union, melting away surface tension.',
    audioPromptPreview: 'Gentle oceanic swell with grounding tanpura harmonics.',
  },
  {
    id: 'med_morning_03',
    title: 'Morning Prana Vitality & Surya Gratitude',
    category: 'Morning Vitality',
    durationMinutes: 5,
    guidanceText: 'Greet the morning sun with gentle Gayatri recitation, awakening spinal prana and setting an intention of boundless patience for the day ahead.',
    audioPromptPreview: 'Vedic morning chanting resonance with gentle stream water.',
  },
];
