// Phase 4: Second Chapter Service & Resource Ecosystem (Module M)

import { SecondChapterProfileDetails, SecondChapterResource } from '../types/secondChapter';
import { UserProfile } from '../types';
import { INITIAL_CONSENT_LEDGER, INITIAL_AUDIT_LOGS } from './chaanbeanVault';

export const INITIAL_USER_SECOND_CHAPTER: SecondChapterProfileDetails = {
  whatILearned: 'I learned that compatibility is not merely about matched hobbies or cultural backgrounds; it is grounded in how two people communicate during tension, how transparent they are about finances, and how much emotional safety they offer each other.',
  whatIWantNow: 'A grounded, mature partner who communicates directly with kindness, values mutual independence, and enjoys creating a peaceful sanctuary at home.',
  whatHasChanged: 'I no longer seek perfection or social validation. I prioritize emotional calm, intellectual resonance, shared integrity, and daily quiet joy.',
  whatIDoNotWantAgain: 'Passive aggression, silence during conflicts instead of calm conversation, financial secrecy, or living to impress extended social circles.',
  myPriorities: [
    'Emotional Stability',
    'Mutual Respect & Equality',
    'Financial Transparency',
    'Peaceful & Gentle Home',
    'Shared Laughter & Companionship',
  ],

  hasChildren: false,
  childrenCount: 0,
  childrenDetails: [],
  custodyArrangement: 'No Children',
  coParentingDynamic: 'Not applicable',
  custodyPrivacy: 'mutual_connections_only',
  openToPartnerWithChildren: true,
  futureChildrenExpectation: 'Open to discussing together',

  griefClosureState: 'Healed & Grounded',
  emotionalIndependence: 'High Sovereignty & Joy',
  readinessAffirmation: true,
  lastAssessedDate: '2026-09-20',
  readinessReflectionNote: 'I have taken the quiet time needed to heal and reflect on my previous journey. I enter this chapter from a place of wholehearted fullness, not loneliness.',
};

export const SECOND_CHAPTER_RESOURCES: SecondChapterResource[] = [
  {
    id: 'res_reset_01',
    pillar: 'RESET',
    pillarTitle: 'Mental Wellbeing & Transition',
    pillarIcon: '🌱',
    title: 'Grief Closure: Reframing Divorce as Growth, Not Defeat',
    subtitle: 'Navigating emotional recovery and breaking free from internalized societal stigma in India.',
    readTime: '6 min read',
    summary: 'Ending a marriage in Indian society is often accompanied by misplaced guilt and collective family anxiety. Real healing begins when we understand that acknowledging an unviable union is an act of courage and self-respect, not moral failure.',
    keyTakeaways: [
      'Divorce is a legal and relational transition, never an indictment of your worth or capacity to love.',
      'Allow yourself to mourn the loss of the dream without staying trapped in resentment toward the past.',
      'Give yourself a minimum buffer of quiet unhurried reflection before stepping into new matchmaking.',
    ],
    actionableChecklist: [
      'Write an uncensored closure letter to your past marriage, then safely destroy or file it away.',
      'Establish a support circle of 2–3 friends or mentors who listen without unsolicited advice.',
      'Schedule a confidential session with a licensed counselor specializing in marital transition.',
    ],
    professionalAssistanceNote: 'MangalSutra maintains an active directory of empathetic, non-judgmental therapists across Bangalore, Mumbai, Delhi NCR, and Chennai.',
  },
  {
    id: 'res_understand_02',
    pillar: 'UNDERSTAND',
    pillarTitle: 'Relational Patterns & Wisdom',
    pillarIcon: '🧠',
    title: 'De-Escalating Recurring Loops: What Went Wrong and Why',
    subtitle: 'Understanding your conflict archetype and choosing conscious communication over defensive reactions.',
    readTime: '8 min read',
    summary: 'Most marriages do not unravel due to sudden catastrophic events, but rather through slow erosion of emotional safety and repeated unresolved conflict cycles. Recognizing your own conflict triggers ensures you do not repeat them in your next chapter.',
    keyTakeaways: [
      'Identify whether you lean towards pursuer (demanding instant answers) or distancer (withdrawing into silence).',
      'Distinguish between core non-negotiable boundaries and trivial everyday differences in style.',
      'Learn the art of the 20-minute de-escalation pause during heated disagreements.',
    ],
    actionableChecklist: [
      'Map your top three personal triggers from past relationship discussions.',
      'Draft a personal "Fair Fighting Pact" specifying how you promise to communicate when upset.',
      'Practice reflective listening: repeating back what your partner said before formulating your reply.',
    ],
  },
  {
    id: 'res_rebuild_03',
    pillar: 'REBUILD',
    pillarTitle: 'Legal & Documentation Clarity',
    pillarIcon: '⚖️',
    title: 'Certified Divorce Decrees & Legal Readiness Under Indian Personal Laws',
    subtitle: 'Essential documentation checklist: Section 13B mutual consent decrees, custody orders, and identity record updates.',
    readTime: '10 min read',
    summary: 'A clean, legally sound foundation is essential before embarking on remarriage. Learn how certified copies of divorce decrees are obtained from Family Courts, the statutory appeal periods, and how to update official records safely.',
    keyTakeaways: [
      'A certified copy of the decree from the Principal Family Court is mandatory before any legal remarriage under the Hindu Marriage Act or Special Marriage Act.',
      'Ensure the statutory 90-day appeal period following a decree has elapsed without appeal before finalizing remarriage.',
      'Decree settlement terms regarding permanent alimony, child maintenance, and physical custody should be clearly indexed.',
    ],
    actionableChecklist: [
      'Secure at least 3 certified true copies of the final judgment and decree from your family court registrar.',
      'Update your name and marital status on PAN, Aadhaar, and Passport with the certified decree copy.',
      'Consolidate banking records and ensure all joint lockers or mortgages from the prior marriage are legally closed.',
    ],
    faqOrLegalNotes: [
      'Section 13B(2) Mutual Consent Decrees: Binding immediately upon pronouncement after waiver or completion of the cooling-off period.',
      'Custody Order Compliance: Even when sole physical custody is granted, visitation clauses remain binding unless modified by the court.',
    ],
    professionalAssistanceNote: 'Need document guidance? ChaanBean connects members with verified Family Law advocates for document audit only—never litigation encouragement.',
  },
  {
    id: 'res_restart_04',
    pillar: 'RESTART',
    pillarTitle: 'Financial Sovereignty & Security',
    pillarIcon: '💰',
    title: 'Financial Sovereignty for Single Parents and Second Chapters',
    subtitle: 'Separating assets, building an emergency buffer, and transparent pre-marital financial conversations.',
    readTime: '7 min read',
    summary: 'Entering a second marriage requires complete financial self-awareness. Having independent savings and clear mutual transparency prevents financial anxiety from affecting your new relationship.',
    keyTakeaways: [
      'Maintain an independent 6-month emergency reserve before entering a new shared household.',
      'Ring-fence existing assets, inherited family properties, and child educational funds transparently.',
      'Agree on proportional household contribution models rather than ambiguous shared pools.',
    ],
    actionableChecklist: [
      'Create an independent mutual fund or fixed deposit portfolio earmarked exclusively for your children’s higher education.',
      'Update nominee designations on your term insurance, provident fund (EPF/PPF), and demat accounts.',
      'Prepare an honest overview of your monthly recurring commitments and loan obligations to share when conversations become serious.',
    ],
  },
  {
    id: 'res_family_05',
    pillar: 'FAMILY',
    pillarTitle: 'Children & Co-Parenting Harmony',
    pillarIcon: '👨‍👩‍👧',
    title: 'Blended Families & Protecting Children’s Emotional Sanctuary',
    subtitle: 'Pacing partner introductions, establishing healthy boundaries, and ensuring children never feel displaced.',
    readTime: '9 min read',
    summary: 'When children are involved, a second marriage is the union of a family system, not merely two individuals. Children need time to adjust and reassurance that their bond with their parent will never be threatened by a new partner.',
    keyTakeaways: [
      'Never introduce a prospective partner to children until both adults have reached mutual commitment and emotional alignment (typically 6–9 months).',
      'The stepparent role should initially be that of a warm, caring mentor or "trusted aunt/uncle", rather than an immediate disciplinarian.',
      'Keep co-parenting discussions with your former spouse strictly child-centric, calm, and free of adult grievances.',
    ],
    actionableChecklist: [
      'Plan the first partner-child meeting in a low-pressure neutral setting (a park, zoo, or casual cafe).',
      'Preserve dedicated 1-on-1 weekly rituals with your child that remain untouched by the new relationship.',
      'Establish clear rules with your new partner regarding boundaries around discipline and school decisions.',
    ],
  },
  {
    id: 'res_reconnect_06',
    pillar: 'RECONNECT',
    pillarTitle: 'Dating & Remarriage with Dignity',
    pillarIcon: '❤️',
    title: 'Stepping Back Into the Arena: Dating with Vulnerability and High Self-Worth',
    subtitle: 'How to share your past story without over-explaining, and how to evaluate prospective partners objectively.',
    readTime: '6 min read',
    summary: 'Second-chapter dating offers a profound advantage: you now know who you are and what you genuinely need. Approach potential partners with head-held-high dignity, neither apologizing for your past nor hiding it.',
    keyTakeaways: [
      'Share your marital history in progressive stages: basic fact in the profile, broad lessons during early chats, detailed realities only when mutual trust is built.',
      'Never tolerate partners or families who make subtle remarks about your divorced or widowed status.',
      'Look for partners who demonstrate active emotional maturity, consistency over time, and kindness towards your boundaries.',
    ],
    actionableChecklist: [
      'Draft a 2-minute graceful explanation of your past marriage that honors the truth without dwelling on bitter details.',
      'Observe how prospective partners treat service staff, their own families, and your schedule.',
      'Trust your instincts: if something felt uncomfortable in your first marriage and reappears, address it immediately.',
    ],
  },
  {
    id: 'res_heal_07',
    pillar: 'HEAL',
    pillarTitle: 'Spiritual Renewal & Pratha Restorative Rituals',
    pillarIcon: '🧘',
    title: 'Inner Renewal: Daily Practices to Restore Peace & Openness',
    subtitle: 'Pratha-inspired mindfulness, somatic release, and spiritual cleansing for a fresh beginning.',
    readTime: '5 min read',
    summary: 'Holding onto bitterness or grief places an invisible weight on the heart. Traditional contemplative practices and gentle daily routines help restore your natural optimism, making space for new love to flourish.',
    keyTakeaways: [
      'Forgiveness is not excusing past harm; it is releasing the emotional hold the past has over your present life.',
      'Morning gratitude and breathwork reset the nervous system from fight-or-flight anxiety to calm receptivity.',
      'Simple sacred rituals (lighting a diya, quiet walking meditation) ground your sense of personal sovereignty.',
    ],
    actionableChecklist: [
      'Practice 10 minutes of morning Anulom Vilom pranayama followed by silent gratitude.',
      'Undertake the 14-day Pratha "Sacred Renewal" reflection series in your personal journal.',
      'Spend a quiet weekend morning visiting a peaceful heritage temple or natural sanctuary alone to recalibrate.',
    ],
  },
];

export const ADDITIONAL_SECOND_CHAPTER_PROFILES: UserProfile[] = [
  {
    id: 'p_vikram_07',
    name: 'Vikramaditya Rathore',
    gender: 'male',
    age: 36,
    dateOfBirth: '1990-08-22',
    intent: 'remarriage',
    maritalStatus: 'widowed',
    religion: 'Hindu',
    community: 'Rajput',
    motherTongue: 'Hindi',
    hometown: 'Udaipur, Rajasthan',
    currentCity: 'Bangalore, Karnataka',
    currentCountry: 'India',
    height: `6' 0" (183 cm)`,
    bio: 'Sustainable architect designing green campuses. Devoted father to an 8-year-old son. After losing my partner four years ago, I have walked a quiet path of healing and fatherhood. Ready to welcome a warm, joyful life partner into our home.',
    education: 'B.Arch & M.Urban Design',
    educationField: 'SPA Delhi & CEPT Ahmedabad',
    profession: 'Partner & Principal Architect',
    companyOrIndustry: 'Sustainable Architecture Studio',
    incomeBracket: '₹50 Lakhs - ₹65 Lakhs / annum',
    incomePrivate: false,
    diet: 'Vegetarian',
    drinking: 'Never',
    smoking: 'Never',
    fitness: 'Cycling, badminton with son, morning yoga',
    interests: ['Heritage Architecture', 'Woodworking', 'Bedtime Stories & Sketching', 'Classical Flute', 'Gardening'],
    familyType: 'Nuclear',
    familyValues: 'Moderate',
    fatherOccupation: 'Retired Judicial Officer (Rajasthan High Court)',
    motherOccupation: 'Homemaker & Social Worker',
    siblings: '1 younger brother (IPS Officer, Jaipur)',
    childrenCount: 1,
    custodyStatus: 'Single parent with 8-year-old son living full-time. Loving grandparents nearby.',
    secondChapterLearnings: 'Life is precious and fragile. I have learned to cherish ordinary daily moments, practice endless patience, and build a peaceful home centered around gentle laughter.',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80',
    additionalPhotos: [],
    photosBlurred: false,
    astrology: {
      dob: '1990-08-22',
      timeOfBirth: '07:15 AM',
      placeOfBirth: 'Udaipur, Rajasthan',
      nakshatra: 'Magha',
      rashi: 'Leo',
      gotra: 'Kashyapa',
      manglikStatus: 'non_manglik',
      horoscopePublic: true,
    },
    expectations: {
      partnerAgeMin: 30,
      partnerAgeMax: 38,
      partnerHeightMin: `5' 2"`,
      partnerEducation: ['Graduate', 'Post Graduate', 'Professional Degree'],
      partnerProfession: ['Design', 'Education', 'Tech', 'Healthcare', 'Arts'],
      partnerLocation: ['Bangalore', 'Jaipur', 'Udaipur', 'Pune'],
      dietaryPreference: 'Vegetarian',
      maritalStatusAccepted: ['divorced', 'widowed', 'never_married'],
      familyValues: 'Moderate',
      childrenExpectations: 'has_children_welcome',
      financialPhilosophy: 'shared_planning',
      relocationOpenness: 'prefer_current',
    },
    trustProfile: {
      trustScoreLevel: 'Comprehensive',
      lastAuditDate: '2026-09-28',
      consentGranted: true,
      visibility: 'mutual_connections_only',
      consentLedger: INITIAL_CONSENT_LEDGER,
      auditLogs: INITIAL_AUDIT_LOGS,
      maritalVerification: {
        declaredStatus: 'widowed',
        declarationAffirmed: true,
        declarationDate: '2026-08-10',
        decreeDate: '2022-04-14',
        courtName: 'Municipal Corporation Registrar of Births & Deaths, Udaipur',
        sectionType: 'Not_Applicable',
        cnrReference: 'RJUD010045122022',
        custodyDisclosedPrivately: 'Sole natural guardian of minor child; verified municipal records.',
        verifiedAt: '2026-08-18',
        verificationBadge: 'Widowed Status Verified with Dignity by ChaanBean Trust',
      },
      checks: [
        { id: 'v_id1', category: 'identity', title: 'Mobile & Email Verified', description: 'Dual factor confirmed', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-08-10' },
        { id: 'v_id2', category: 'identity', title: 'Aadhaar Biometric Check', description: 'UIDAI XML authenticated', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-08-12' },
        { id: 'v_id3', category: 'education', title: 'Council of Architecture Registry', description: 'License authenticated', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-08-15' },
        { id: 'v_id4', category: 'marital_status', title: 'Municipal Certificate Verification', description: 'Certified municipal record', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-08-18' },
      ],
    },
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'p_ananya_08',
    name: 'Ananya Deshpande',
    gender: 'female',
    age: 34,
    dateOfBirth: '1992-03-10',
    intent: 'remarriage',
    maritalStatus: 'divorced',
    religion: 'Hindu',
    community: 'Marathi Brahmin',
    motherTongue: 'Marathi',
    hometown: 'Pune, Maharashtra',
    currentCity: 'Bangalore, Karnataka',
    currentCountry: 'India',
    height: `5' 6" (167 cm)`,
    bio: 'Director of AI Engineering at a healthtech startup. Solo traveler, amateur ceramicist, and marathon enthusiast. Divorced amicably 3 years ago without children. Looking for an emotionally intelligent, progressive life partner who values authentic dialogue and mutual independence.',
    education: 'B.Tech (COEP Pune) & M.S. Computer Science (Georgia Tech)',
    educationField: 'COEP & Georgia Tech',
    profession: 'Engineering Director, AI',
    companyOrIndustry: 'HealthTech AI',
    incomeBracket: '₹60 Lakhs - ₹80 Lakhs / annum',
    incomePrivate: false,
    diet: 'Eggetarian',
    drinking: 'Occasionally',
    smoking: 'Never',
    fitness: 'Crossfit 3x/week, 10k runner',
    interests: ['Ceramics & Pottery', 'AI Ethics', 'Trail Running', 'Specialty Coffee', 'Sufi Poetry'],
    familyType: 'Nuclear',
    familyValues: 'Liberal',
    fatherOccupation: 'Retired Scientist, DRDO',
    motherOccupation: 'Principal, High School Pune',
    siblings: '1 elder brother (Tech Lead in Seattle)',
    childrenCount: 0,
    custodyStatus: 'No children. Complete mutual Section 13B decree finalized in 2023.',
    secondChapterLearnings: 'I learned that shared intellectual curiosity must be anchored by emotional honesty. I know my boundaries, celebrate my partner’s independence, and cherish honest communication without games.',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    additionalPhotos: [],
    photosBlurred: false,
    astrology: {
      dob: '1992-03-10',
      timeOfBirth: '10:45 AM',
      placeOfBirth: 'Pune, Maharashtra',
      nakshatra: 'Rohini',
      rashi: 'Taurus',
      gotra: 'Vashishta',
      manglikStatus: 'non_manglik',
      horoscopePublic: true,
    },
    expectations: {
      partnerAgeMin: 32,
      partnerAgeMax: 41,
      partnerHeightMin: `5' 8"`,
      partnerEducation: ['Post Graduate', 'Professional Degree', 'Doctorate'],
      partnerProfession: ['Tech', 'Academia', 'Entrepreneurship', 'Product', 'Design'],
      partnerLocation: ['Bangalore', 'Pune', 'Mumbai', 'Hyderabad'],
      dietaryPreference: 'Any',
      maritalStatusAccepted: ['divorced', 'widowed', 'never_married'],
      familyValues: 'Liberal',
      childrenExpectations: 'open_to_children',
      financialPhilosophy: 'independent_accounts',
      relocationOpenness: 'open',
    },
    trustProfile: {
      trustScoreLevel: 'Comprehensive',
      lastAuditDate: '2026-10-01',
      consentGranted: true,
      visibility: 'mutual_connections_only',
      consentLedger: INITIAL_CONSENT_LEDGER,
      auditLogs: INITIAL_AUDIT_LOGS,
      maritalVerification: {
        declaredStatus: 'divorced',
        declarationAffirmed: true,
        declarationDate: '2026-07-20',
        decreeDate: '2023-09-12',
        courtName: 'Family Court, Pune',
        sectionType: '13B_Mutual_Consent',
        cnrReference: 'MHPU020056122023',
        verifiedAt: '2026-07-28',
        verificationBadge: 'Divorce Status Verified by ChaanBean Trust',
      },
      checks: [
        { id: 'an_1', category: 'identity', title: 'Mobile & Corporate Email Verified', description: 'Dual factor confirmed', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-07-20' },
        { id: 'an_2', category: 'identity', title: 'Passport & Aadhaar Verified', description: 'DigiLocker biometric record', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-07-22' },
        { id: 'an_3', category: 'education', title: 'COEP & Georgia Tech Degree Auth', description: 'National Academic Depository authenticated', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-07-25' },
        { id: 'an_4', category: 'marital_status', title: 'Certified Section 13B Decree Audit', description: 'Pune Family Court certified decree verified', status: 'verified', visibility: 'mutual_connections_only', verifiedAt: '2026-07-28' },
      ],
    },
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-10-01T12:00:00Z',
  },
];
